# Generated by Django 4.1.3 on 2022-11-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guruapp', '0002_shop_qtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='qtitle',
            new_name='title',
        ),
    ]
