# Generated by Django 4.1.3 on 2022-11-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guruapp', '0004_alter_shop_time_closed_alter_shop_time_open'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Town',
            new_name='City',
        ),
    ]
