# Generated by Django 4.1.3 on 2022-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guruapp', '0003_rename_qtitle_shop_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='time_closed',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='time_open',
            field=models.TimeField(),
        ),
    ]
