# Generated by Django 4.1.3 on 2022-11-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guruapp', '0005_rename_town_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='town',
            new_name='city',
        ),
    ]
